name: node.js CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: npm install and npm run build --prod
        run: |
          npm i
          npm run build:prod
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist"
    
 
        
        

